kind: ConfigMap
apiVersion: v1
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: build-config
  namespace: go-demo-3-build
data:
  build-config.properties: |
    project=go-demo-3
    image=sikor1111/go-demo-3
    domain=192.168.99.100.nip.io
    addr=go-demo-3.192.168.99.100.nip.io
    cmAddr=cm.192.168.99.100.nip.io
    chartVer=0.0.1

